# -*- coding: utf-8 -*-
"""movie_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kHaDkRFNtB0MepZ_5VnTqnx-RQVdNKUR
"""

!pip install pyspark

from google.colab import drive
drive.mount('/content/movies.dat')

from pyspark.sql.context import SQLContext
#start spark session
from pyspark.sql.types import*
from pyspark import SparkConf
from pyspark.sql import SparkSession
from pyspark.sql.functions import max,desc,avg,col
spark = SparkSession.builder.master("local").appName("movies").getOrCreate()

sc = spark.sparkContext

move_details = spark.sparkContext.textFile("/content/movies.dat")

movie_schema = (StructType() .add("move_id", IntegerType()) .add("titele", StringType()) .add("genres",StringType()))

move_details = move_details.map(lambda x: x.split("::"))

movie_information = move_details.map(lambda x: (int(x[0]), x[1], x[2].strip()))

movies = spark.createDataFrame(movie_information, movie_schema)

movies.show(5)

rating_details = spark.sparkContext.textFile("/content/ratings.dat")

from pyspark.sql.types import StructType, IntegerType, StringType

Schema = StructType() \
    .add("user_id", IntegerType()) \
    .add("movie_id", IntegerType()) \
    .add("rating", IntegerType()) \
    .add("timestamp", StringType())

rating_details = rating_details.map(lambda x: x.split("::"))

movie_information2 = rating_details.map(lambda p: (int(p[0], p[1], float(p[2]).p[3].strip())))

movie_information2 = rating_details.map(lambda p: (int(p[0]), int(p[1]), int(p[2]), p[3]))
rating = spark.createDataFrame(movie_information2, Schema )

!head /content/ratings.dat

rating_details = sc.textFile("/content/ratings.dat")
rating_details.take(5)

rating_rdd = rating_details.map(lambda x: x.split("::")) \
    .map(lambda x: (
        int(x[0]),
        int(x[1]),
        int(x[2]),
        x[3]
    ))

rating = spark.createDataFrame(rating_rdd, Schema)
rating.show(5)

movies.printSchema() #display the structure (schema)

rating.describe().show() #get summary statistics of your DataFrame and display them.

#most popular movies
from pyspark.sql.functions import *
most_popular = rating\
.groupBy("movie_id")\
.agg(count("user_id"))\
.withColumnRenamed("count(user_id)", "count")\
.orderBy(desc("count"))

most_popular.show()

movies.columns

most_popular.columns

movies = movies.withColumnRenamed("move_id", "movie_id")

movies.columns

most_popular = most_popular.join(
    movies,
    "movie_id"
)

most_popular = most_popular.join(
    movies,
    most_popular.movie_id == movies.movie_id
)

most_popular.printSchema()

most_popular.orderBy(desc("count")).show(10, False)

most_popular.join(movies, "movie_id")

most_popular = rating.groupBy("movie_id") \
                      .count() \
                      .withColumnRenamed("count","number_of_ratings")

movies = movies.withColumnRenamed("move_id","movie_id")
movies = movies.withColumnRenamed("titele","title")

result = most_popular.join(
            movies,
            "movie_id"
         ).orderBy(
            desc("number_of_ratings")
         )

result.show()

#average Rating
average_rating = rating.groupBy("movie_id")\
.agg(avg("rating"))\
.withColumnRenamed("avg(rating)", "avg_rating")

average_rating.show()

top_rated_movies = average_rating.join(movies, ["movie_id"])
top_rated_movies.show(10)

#top rating
top_rated = rating\
.groupBy("movie_id")\
.agg(
    count("user_id").alias("num_rating"),
    avg(col("rating")).alias("avg_rating")
    )
top_rated_movies = top_rated.join(movies, "movie_id").sort(desc("avg_rating"),desc("num_rating"))

top_rated_movies.show(10)

top_rated_movies.where("num_rating > 500").show(20, truncate=False)
top_rated_movies.write.save("top_rated_movies")

#most polarising movies
#it gives  both positive talk and negative talk  of movies
rating_stdev = rating\
.groupBy("movie_id")\
.agg(count("user_id").alias("num_rating"),
    avg(col("rating")).alias("avg_rating"),
    stddev(col("rating")).alias("std_rating"))\
.where("num_rating > 500")

marmite_movies = rating_stdev.join(movies, "movie_id")

marmite_movies.sort(desc("std_rating")).show(15, truncate=False)
marmite_movies.write.save("marmite_movies")

rating.createOrReplaceTempView("rating")
movies.createOrReplaceTempView("movies")

spark.sql("SELECT * FROM rating").show(5)

spark.sql("SELECT * FROM movieS").show(5)

moving_rating = spark.sql("""
SELECT
    rating,
    COUNT(rating) AS number_of_movies_per_rating
FROM rating
GROUP BY rating
ORDER BY rating ASC
""")

moving_rating.show(10)

moving_rating.write.mode("overwrite").save("movie_rating")

movie_analysis = spark.sql("""
SELECT
    movie_id,
    COUNT(user_id) AS total_number_of_users,
    SUM(rating) AS total_ratings,
    CAST(AVG(rating) AS DECIMAL(16,2)) AS average_ratings
FROM rating
GROUP BY movie_id
ORDER BY CAST(movie_id AS INT) ASC
""")
movie_analysis.show(10)
movie_analysis.registerTempTable("movie_analysis")

movie_avg_ratings = spark.sql("""
SELECT
    m.movie_id,
    a.total_number_of_users,
    a.total_ratings,
    a.average_ratings
FROM movies m
JOIN movie_analysis a
    ON m.movie_id = a.movie_id
ORDER BY a.average_ratings DESC
""")
movie_avg_ratings.show(10)
movie_avg_ratings.write.mode("overwrite").save("movie_avg_ratings")

spark-submit \
--master yarn \
--deploy-mode cluster \
--executor-memory 10G \
--num-executors 20 \
--driver-memory 20G \
--conf spark.executor.cores=4 \
movie_analysis.py

spark-submit movie_analysis.py

!mkdir -p movie_project/config
!mkdir -p movie_project/data
!mkdir -p movie_project/output

from google.colab import files
files.upload()

!mv ratings.csv movie_project/data/
!mv movies.csv movie_project/data/